import Layout from '@/component/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/developer-pic-1.png"
import AnimatedText from '@/component/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/component/Icons'
import HireMe from '@/component/HireMe'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
            <div className='flex items-center justify-between w-full'>
                <div className='w-1/2'>
                  <Image src={profilePic} alt='CodeBucks' className='w-full h-auto'/>
                </div>
                <div className='w-1/2 flex flex-col items-center self-center'>
                  <AnimatedText text="Carlos Aaron Benites Acevedo" className='!text-6xl !text-left'/>
                  <p className='my-4 text-base font-medium'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                  </p>
                  <div className='flex items-center self-start mt-2'>
                    <Link href="/dummy.pdf" target={"_blank"} 
                    className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark'
                    download={true}>
                      Resume <LinkArrow className={"w-6 ml-1"}/>
                      </Link>
                     <Link href="mailto:abcd@gmail.com" target={"_blank"}
                     className='ml-4 text-lg font-medium capitalize text-dark underline'
                     >Contact</Link>
                  </div>
                </div>
            </div>
        </Layout>
        <HireMe/>
      </main>
    </>
  )
}
